j-antplus: Add javax as dependency
Seems the package is split in two. Need this otherwise we run into this
exception:

be.glever.ant.AntException: javax.usb.UsbException: The UsbServices implementation class org.usb4java.javax.Services was not found : org.usb4java.javax.Services
        at be.glever.ant.usb.AntUsbDeviceFactory.getAvailableAntDevices(AntUsbDeviceFactory.java:35)
        at me.danielschaefer.sensorwrangler.sensors.AntPlusSensor$specificConnect$1.invoke(AntPlusSensor.kt:15)
        at me.danielschaefer.sensorwrangler.sensors.AntPlusSensor$specificConnect$1.invoke(AntPlusSensor.kt:14)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: javax.usb.UsbException: The UsbServices implementation class org.usb4java.javax.Services was not found : org.usb4java.javax.Services
        at javax.usb.UsbHostManager.createUsbServices(Unknown Source)
        at javax.usb.UsbHostManager.getUsbServices(Unknown Source)
        at be.glever.ant.usb.AntUsbDeviceFactory.getAvailableAntDevices(AntUsbDeviceFactory.java:31)
        ... 3 more